//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\maszyd\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://mszydlo.api.crm4.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"CrmEarlyBound" /out:"C:\Users\maszyd\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"mszydlo@mszydlo.onmicrosoft.com" /password:"**************" 
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{


    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_AccountCategoryCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Preferowany_klient = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Standardowe = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_AccountClassificationCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wartosc_domyslna = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_AccountRatingCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wartosc_domyslna = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_Address1_AddressTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dostawa = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inne = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Podstawowy = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rachunek_dla = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_Address1_FreightTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FCA___franco_przewoznik = 14,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Franco_statek__FOB_ = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_Address1_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DHL = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Poczta_lotnicza = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Poczta_tradycyjna = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pocztex = 22,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Servisco = 21,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stolica = 20,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        UPS = 4,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_Address2_AddressTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wartosc_domyslna = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_Address2_FreightTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wartosc_domyslna = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_Address2_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wartosc_domyslna = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_BusinessTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wartosc_domyslna = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_CustomerSizeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wartosc_domyslna = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_CustomerTypeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dostawca__producent_ = 10,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dostawca__sprzedawca_ = 11,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ewentualny_klient = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inne = 12,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inwestor = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Klient = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Konkurent = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Konsultant = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Odsprzedawca = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Osoba_majaca_wplyw = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Partner = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prasa = 7,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_IndustryCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bankowosc = 81,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Budownictwo = 53,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Doradztwo = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dystrybucja = 80,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gornictwo = 50,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Informatyka = 74,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Media = 195,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nieruchomosci = 82,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Petrochemia = 24,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Produkcja_zywnosci = 79,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rachunkowosc = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rolnictwo = 49,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Szpitalnictwo = 78,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transport = 30,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ubezpieczenia = 20,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_OwnershipCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inne = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prywatny = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Publiczne = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spoleczny = 11,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_PaymentTermsCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        _14_dni = 7,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        _30_dni = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        _60_dni = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        _7_dni = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        _90_dni = 9,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Platne_przy_odbiorze = 30,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_PreferredAppointmentDayCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Czwartek = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Niedziela = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Piatek = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Poniedzialek = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sobota = 6,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sroda = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wtorek = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_PreferredAppointmentTimeCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Po_poludniu = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rano = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wieczor = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_PreferredContactMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adres_email = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dowolna = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Faks = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Poczta = 5,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Telefon = 3,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_ShippingMethodCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wartosc_domyslna = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_StatusCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aktywne = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nieaktywne = 2,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum Account_TerritoryCode
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Wartosc_domyslna = 1,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum msdyn_travelchargetype
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Brak = 690970003,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Co_godzine = 690970000,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Przebieg = 690970001,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stala = 690970002,
    }

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
    public enum msdyn_msdyn_requirementrelationship_msdyn_resourcegroupings
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jednostka_organizacyjna = 192350000,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Powiazane_pule_zasobow = 192350001,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lokalizacja = 192350002,
    }
}
